#base image
FROM python:3

#
ENV PYTHONBUFFERED 1

# Working direqctory
WORKDIR /app

# Add all the stuff we need to the container
ADD . /app
## copy to 
COPY ./requirements.txt /app/requirements.txt
